#!/usr/bin/env python3
"""
gen_shim.py — read CSTech2Win.dll's export table and emit:
    src/cstech2win.def      — module-definition file controlling export names
    src/forwarders.c        — forwarder stubs for non-instrumented exports
    src/wrappers.h          — function pointer typedefs for instrumented wrappers

Run from anywhere. Writes into ../src/ relative to this script.

The shim's design:
    Tech2Win (or any D-PDU client) loads CSTech2Win.dll from its install dir.
    We replace that DLL with our shim. The shim:
      1. On DllMain attach, LoadLibrary("CSTech2Win_real.dll") and resolve all 29 PDU* exports.
      2. For most exports, forward the call verbatim to the real DLL via __stdcall trampolines.
      3. For instrumented exports (PDUStartComPrimitive, PDUGetEventItem, etc.),
         log args + output buffers, then forward.

We classify exports into two buckets:
    INSTRUMENTED — wrappers we hand-write in src/wrappers.c with full logging.
    PASSTHROUGH  — auto-generated forwarders, no logging.

This script generates the PASSTHROUGH stubs and the .def file. Wrapped functions
are defined manually in src/wrappers.c and listed in INSTRUMENTED below — they
are excluded from auto-generation.
"""
import argparse
import sys
from pathlib import Path

try:
    import pefile
except ImportError:
    print("ERROR: pip install pefile", file=sys.stderr)
    sys.exit(2)


# Functions we instrument by hand. All others get auto-generated forwarders.
INSTRUMENTED = {
    "PDUStartComPrimitive",      # carries the SecurityAccess request bytes
    "PDUGetEventItem",           # carries the seed/key response bytes
    "PDURegisterEventCallback",  # async response path
    "PDUIoCtl",                  # config (bitrate, filters)
    "PDUSetComParam",            # ProtocolID/baud/J1962_PINS for Android init recipe
    "PDUConstruct",              # API init — log version/options
    "PDUDestruct",
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("dll", help="Path to real CSTech2Win.dll to read exports from")
    ap.add_argument("--out-dir", default=None, help="Output dir (default: ../src/)")
    args = ap.parse_args()

    out_dir = Path(args.out_dir) if args.out_dir else Path(__file__).parent.parent / "src"
    out_dir.mkdir(parents=True, exist_ok=True)

    pe = pefile.PE(args.dll)
    if not hasattr(pe, "DIRECTORY_ENTRY_EXPORT"):
        print(f"ERROR: {args.dll} has no export table", file=sys.stderr)
        return 1

    exports = []
    for e in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if not e.name:
            continue
        exports.append((e.ordinal, e.name.decode()))
    exports.sort(key=lambda x: x[0])

    if pe.FILE_HEADER.Machine != 0x14c:
        print(f"WARN: DLL machine type 0x{pe.FILE_HEADER.Machine:04x} is not x86; shim assumes 32-bit", file=sys.stderr)

    print(f"Read {len(exports)} exports from {args.dll}")

    # -- 1. Module-definition file --------------------------------------------
    def_path = out_dir / "cstech2win.def"
    with def_path.open("w", encoding="utf-8") as f:
        f.write("; Auto-generated by gen_shim.py — DO NOT EDIT BY HAND\n")
        f.write("; Re-generate from CSTech2Win.dll if exports change.\n")
        f.write("LIBRARY CSTech2Win\n")
        f.write("EXPORTS\n")
        for ordinal, name in exports:
            f.write(f"    {name:<32}@{ordinal}\n")
    print(f"  wrote {def_path}")

    # -- 2. Forwarder C source -------------------------------------------------
    fwd_path = out_dir / "forwarders.c"
    passthrough = [(o, n) for o, n in exports if n not in INSTRUMENTED]
    with fwd_path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by gen_shim.py — DO NOT EDIT BY HAND\n")
        f.write("// Forwarders for D-PDU exports that we don't instrument.\n")
        f.write("// Each stub is naked: it jumps to the resolved real-DLL function\n")
        f.write("// pointer with the original stack intact, so the calling convention\n")
        f.write("// (__stdcall, varies arg count) is preserved without our knowing it.\n\n")
        f.write('#include "shim.h"\n\n')
        for ordinal, name in passthrough:
            f.write(f"FARPROC g_real_{name} = NULL;\n")
        f.write("\n")
        f.write("void resolve_passthrough_exports(HMODULE hReal) {\n")
        for ordinal, name in passthrough:
            f.write(f'    g_real_{name} = GetProcAddress(hReal, "{name}");\n')
        f.write("}\n\n")
        for ordinal, name in passthrough:
            f.write(f"// {name} (ord {ordinal}) — forwarder\n")
            f.write(f"__attribute__((naked)) void {name}(void) {{\n")
            f.write(f"    __asm__ __volatile__ (\n")
            f.write(f'        "jmp *%0\\n"\n')
            f.write(f'        : : "m" (g_real_{name})\n')
            f.write(f"    );\n")
            f.write(f"}}\n\n")
    print(f"  wrote {fwd_path} ({len(passthrough)} forwarders)")

    # -- 3. Wrapper header (typedefs for instrumented funcs) -------------------
    hdr_path = out_dir / "wrappers.h"
    with hdr_path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by gen_shim.py — function pointer typedefs\n")
        f.write("// for the instrumented exports. Real signatures from ISO 22900-2.\n\n")
        f.write("#ifndef CSTECH2WIN_SHIM_WRAPPERS_H\n")
        f.write("#define CSTECH2WIN_SHIM_WRAPPERS_H\n\n")
        f.write('#include "shim.h"\n\n')
        f.write("// Real-DLL function pointers for the wrapped exports.\n")
        f.write("// Populated by resolve_instrumented_exports() in wrappers.c.\n")
        for name in sorted(INSTRUMENTED):
            f.write(f"extern FARPROC g_real_{name};\n")
        f.write("\n")
        f.write("void resolve_instrumented_exports(HMODULE hReal);\n\n")
        f.write("#endif\n")
    print(f"  wrote {hdr_path}")

    # -- 4. Summary ------------------------------------------------------------
    print()
    print(f"Total exports     : {len(exports)}")
    print(f"  Forwarders      : {len(passthrough)}")
    print(f"  Instrumented    : {len(INSTRUMENTED)} (hand-written in src/wrappers.c)")
    missing = INSTRUMENTED - {n for _, n in exports}
    if missing:
        print(f"\n  WARNING: instrumented names NOT in DLL: {missing}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
