// Auto-generated by gen_shim.py — DO NOT EDIT BY HAND
// Forwarders for D-PDU exports that we don't instrument.
// Each stub is naked: it jumps to the resolved real-DLL function
// pointer with the original stack intact, so the calling convention
// (__stdcall, varies arg count) is preserved without our knowing it.

#include "shim.h"

FARPROC g_real_PDUCancelComPrimitive = NULL;
FARPROC g_real_PDUConnect = NULL;
FARPROC g_real_PDUCreateComLogicalLink = NULL;
FARPROC g_real_PDUDestroyComLogicalLink = NULL;
FARPROC g_real_PDUDestroyItem = NULL;
FARPROC g_real_PDUDisconnect = NULL;
FARPROC g_real_PDUGetComParam = NULL;
FARPROC g_real_PDUGetConflictingResources = NULL;
FARPROC g_real_PDUGetLastError = NULL;
FARPROC g_real_PDUGetModuleIds = NULL;
FARPROC g_real_PDUGetObjectId = NULL;
FARPROC g_real_PDUGetResourceIds = NULL;
FARPROC g_real_PDUGetResourceStatus = NULL;
FARPROC g_real_PDUGetStatus = NULL;
FARPROC g_real_PDUGetTimestamp = NULL;
FARPROC g_real_PDUGetUniqueRespIdTable = NULL;
FARPROC g_real_PDUGetVersion = NULL;
FARPROC g_real_PDULockResource = NULL;
FARPROC g_real_PDUModuleConnect = NULL;
FARPROC g_real_PDUModuleDisconnect = NULL;
FARPROC g_real_PDUSetUniqueRespIdTable = NULL;
FARPROC g_real_PDUUnlockResource = NULL;

void resolve_passthrough_exports(HMODULE hReal) {
    g_real_PDUCancelComPrimitive = GetProcAddress(hReal, "PDUCancelComPrimitive");
    g_real_PDUConnect = GetProcAddress(hReal, "PDUConnect");
    g_real_PDUCreateComLogicalLink = GetProcAddress(hReal, "PDUCreateComLogicalLink");
    g_real_PDUDestroyComLogicalLink = GetProcAddress(hReal, "PDUDestroyComLogicalLink");
    g_real_PDUDestroyItem = GetProcAddress(hReal, "PDUDestroyItem");
    g_real_PDUDisconnect = GetProcAddress(hReal, "PDUDisconnect");
    g_real_PDUGetComParam = GetProcAddress(hReal, "PDUGetComParam");
    g_real_PDUGetConflictingResources = GetProcAddress(hReal, "PDUGetConflictingResources");
    g_real_PDUGetLastError = GetProcAddress(hReal, "PDUGetLastError");
    g_real_PDUGetModuleIds = GetProcAddress(hReal, "PDUGetModuleIds");
    g_real_PDUGetObjectId = GetProcAddress(hReal, "PDUGetObjectId");
    g_real_PDUGetResourceIds = GetProcAddress(hReal, "PDUGetResourceIds");
    g_real_PDUGetResourceStatus = GetProcAddress(hReal, "PDUGetResourceStatus");
    g_real_PDUGetStatus = GetProcAddress(hReal, "PDUGetStatus");
    g_real_PDUGetTimestamp = GetProcAddress(hReal, "PDUGetTimestamp");
    g_real_PDUGetUniqueRespIdTable = GetProcAddress(hReal, "PDUGetUniqueRespIdTable");
    g_real_PDUGetVersion = GetProcAddress(hReal, "PDUGetVersion");
    g_real_PDULockResource = GetProcAddress(hReal, "PDULockResource");
    g_real_PDUModuleConnect = GetProcAddress(hReal, "PDUModuleConnect");
    g_real_PDUModuleDisconnect = GetProcAddress(hReal, "PDUModuleDisconnect");
    g_real_PDUSetUniqueRespIdTable = GetProcAddress(hReal, "PDUSetUniqueRespIdTable");
    g_real_PDUUnlockResource = GetProcAddress(hReal, "PDUUnlockResource");
}

// PDUCancelComPrimitive (ord 1) — forwarder
__attribute__((naked)) void PDUCancelComPrimitive(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUCancelComPrimitive)
    );
}

// PDUConnect (ord 2) — forwarder
__attribute__((naked)) void PDUConnect(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUConnect)
    );
}

// PDUCreateComLogicalLink (ord 4) — forwarder
__attribute__((naked)) void PDUCreateComLogicalLink(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUCreateComLogicalLink)
    );
}

// PDUDestroyComLogicalLink (ord 5) — forwarder
__attribute__((naked)) void PDUDestroyComLogicalLink(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUDestroyComLogicalLink)
    );
}

// PDUDestroyItem (ord 6) — forwarder
__attribute__((naked)) void PDUDestroyItem(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUDestroyItem)
    );
}

// PDUDisconnect (ord 8) — forwarder
__attribute__((naked)) void PDUDisconnect(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUDisconnect)
    );
}

// PDUGetComParam (ord 9) — forwarder
__attribute__((naked)) void PDUGetComParam(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUGetComParam)
    );
}

// PDUGetConflictingResources (ord 10) — forwarder
__attribute__((naked)) void PDUGetConflictingResources(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUGetConflictingResources)
    );
}

// PDUGetLastError (ord 12) — forwarder
__attribute__((naked)) void PDUGetLastError(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUGetLastError)
    );
}

// PDUGetModuleIds (ord 13) — forwarder
__attribute__((naked)) void PDUGetModuleIds(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUGetModuleIds)
    );
}

// PDUGetObjectId (ord 14) — forwarder
__attribute__((naked)) void PDUGetObjectId(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUGetObjectId)
    );
}

// PDUGetResourceIds (ord 15) — forwarder
__attribute__((naked)) void PDUGetResourceIds(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUGetResourceIds)
    );
}

// PDUGetResourceStatus (ord 16) — forwarder
__attribute__((naked)) void PDUGetResourceStatus(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUGetResourceStatus)
    );
}

// PDUGetStatus (ord 17) — forwarder
__attribute__((naked)) void PDUGetStatus(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUGetStatus)
    );
}

// PDUGetTimestamp (ord 18) — forwarder
__attribute__((naked)) void PDUGetTimestamp(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUGetTimestamp)
    );
}

// PDUGetUniqueRespIdTable (ord 19) — forwarder
__attribute__((naked)) void PDUGetUniqueRespIdTable(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUGetUniqueRespIdTable)
    );
}

// PDUGetVersion (ord 20) — forwarder
__attribute__((naked)) void PDUGetVersion(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUGetVersion)
    );
}

// PDULockResource (ord 22) — forwarder
__attribute__((naked)) void PDULockResource(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDULockResource)
    );
}

// PDUModuleConnect (ord 23) — forwarder
__attribute__((naked)) void PDUModuleConnect(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUModuleConnect)
    );
}

// PDUModuleDisconnect (ord 24) — forwarder
__attribute__((naked)) void PDUModuleDisconnect(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUModuleDisconnect)
    );
}

// PDUSetUniqueRespIdTable (ord 27) — forwarder
__attribute__((naked)) void PDUSetUniqueRespIdTable(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUSetUniqueRespIdTable)
    );
}

// PDUUnlockResource (ord 29) — forwarder
__attribute__((naked)) void PDUUnlockResource(void) {
    __asm__ __volatile__ (
        "jmp *%0\n"
        : : "m" (g_real_PDUUnlockResource)
    );
}

