// Auto-generated by gen_shim.py — function pointer typedefs
// for the instrumented exports. Real signatures from ISO 22900-2.

#ifndef CSTECH2WIN_SHIM_WRAPPERS_H
#define CSTECH2WIN_SHIM_WRAPPERS_H

#include "shim.h"

// Real-DLL function pointers for the wrapped exports.
// Populated by resolve_instrumented_exports() in wrappers.c.
extern FARPROC g_real_PDUConstruct;
extern FARPROC g_real_PDUDestruct;
extern FARPROC g_real_PDUGetEventItem;
extern FARPROC g_real_PDUIoCtl;
extern FARPROC g_real_PDURegisterEventCallback;
extern FARPROC g_real_PDUSetComParam;
extern FARPROC g_real_PDUStartComPrimitive;

void resolve_instrumented_exports(HMODULE hReal);

#endif
